import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootApp = join(__dirname, '..');

const candidatePaths = [
  'D:/Users/HKD1/.gemini/antigravity/brain/07a08571-3fbe-48a4-b13d-84d5fd14b466/.user_uploaded/media_1789354253411.jpg',
  join(rootApp, 'src', 'assets', 'logo-thue.jpg'),
  join(rootApp, 'public', 'logo-thue.jpg'),
];

let sourcePath = candidatePaths.find((p) => existsSync(p));

const compDir = join(rootApp, 'src', 'components');
const assetsDir = join(rootApp, 'src', 'assets');
const publicDir = join(rootApp, 'public');

if (!existsSync(compDir)) mkdirSync(compDir, { recursive: true });
if (!existsSync(assetsDir)) mkdirSync(assetsDir, { recursive: true });
if (!existsSync(publicDir)) mkdirSync(publicDir, { recursive: true });

if (sourcePath) {
  try {
    const imgBuffer = readFileSync(sourcePath);
    const base64 = `data:image/jpeg;base64,${imgBuffer.toString('base64')}`;

    // Save to assets and public
    copyFileSync(sourcePath, join(assetsDir, 'logo-thue.jpg'));
    copyFileSync(sourcePath, join(publicDir, 'logo-thue.jpg'));

    const code = `// Auto-generated by scripts/prepare-logo.mjs\nexport const TAX_LOGO_BASE64 = ${JSON.stringify(base64)};\n`;
    writeFileSync(join(compDir, 'taxLogoData.ts'), code, 'utf8');
    console.log(`[prepare-logo] Successfully embedded official Tax Logo (${imgBuffer.length} bytes) to src/components/taxLogoData.ts`);
  } catch (err) {
    console.error('[prepare-logo] Error processing logo:', err);
  }
} else {
  console.log('[prepare-logo] No source logo found, keeping existing taxLogoData.ts');
}

// Synchronize Excel templates and inspection KPI data
try {
  const { syncExcelTemplatesAndKpi } = await import('./sync-excel-templates.mjs');
  await syncExcelTemplatesAndKpi();
} catch (err) {
  console.error('[prepare-logo] Error during syncExcelTemplatesAndKpi:', err);
}
